/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type CreatePublicationResponse = components.ErrorT | components.Publication;

/** @internal */
export const CreatePublicationResponse$inboundSchema: z.ZodType<
    CreatePublicationResponse,
    z.ZodTypeDef,
    unknown
> = z.union([components.ErrorT$inboundSchema, components.Publication$inboundSchema]);

/** @internal */
export type CreatePublicationResponse$Outbound =
    | components.ErrorT$Outbound
    | components.Publication$Outbound;

/** @internal */
export const CreatePublicationResponse$outboundSchema: z.ZodType<
    CreatePublicationResponse$Outbound,
    z.ZodTypeDef,
    CreatePublicationResponse
> = z.union([components.ErrorT$outboundSchema, components.Publication$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreatePublicationResponse$ {
    /** @deprecated use `CreatePublicationResponse$inboundSchema` instead. */
    export const inboundSchema = CreatePublicationResponse$inboundSchema;
    /** @deprecated use `CreatePublicationResponse$outboundSchema` instead. */
    export const outboundSchema = CreatePublicationResponse$outboundSchema;
    /** @deprecated use `CreatePublicationResponse$Outbound` instead. */
    export type Outbound = CreatePublicationResponse$Outbound;
}
