/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type GetOrderRequest = {
    id: string;
};

export type GetOrderResponse = components.ErrorT | components.Order;

/** @internal */
export const GetOrderRequest$inboundSchema: z.ZodType<GetOrderRequest, z.ZodTypeDef, unknown> =
    z.object({
        id: z.string(),
    });

/** @internal */
export type GetOrderRequest$Outbound = {
    id: string;
};

/** @internal */
export const GetOrderRequest$outboundSchema: z.ZodType<
    GetOrderRequest$Outbound,
    z.ZodTypeDef,
    GetOrderRequest
> = z.object({
    id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrderRequest$ {
    /** @deprecated use `GetOrderRequest$inboundSchema` instead. */
    export const inboundSchema = GetOrderRequest$inboundSchema;
    /** @deprecated use `GetOrderRequest$outboundSchema` instead. */
    export const outboundSchema = GetOrderRequest$outboundSchema;
    /** @deprecated use `GetOrderRequest$Outbound` instead. */
    export type Outbound = GetOrderRequest$Outbound;
}

/** @internal */
export const GetOrderResponse$inboundSchema: z.ZodType<GetOrderResponse, z.ZodTypeDef, unknown> =
    z.union([components.ErrorT$inboundSchema, components.Order$inboundSchema]);

/** @internal */
export type GetOrderResponse$Outbound = components.ErrorT$Outbound | components.Order$Outbound;

/** @internal */
export const GetOrderResponse$outboundSchema: z.ZodType<
    GetOrderResponse$Outbound,
    z.ZodTypeDef,
    GetOrderResponse
> = z.union([components.ErrorT$outboundSchema, components.Order$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrderResponse$ {
    /** @deprecated use `GetOrderResponse$inboundSchema` instead. */
    export const inboundSchema = GetOrderResponse$inboundSchema;
    /** @deprecated use `GetOrderResponse$outboundSchema` instead. */
    export const outboundSchema = GetOrderResponse$outboundSchema;
    /** @deprecated use `GetOrderResponse$Outbound` instead. */
    export type Outbound = GetOrderResponse$Outbound;
}
