/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components/index.js";
import * as z from "zod";

export type GetPublicationRequest = {
    id: string;
};

export type GetPublicationResponse = components.ErrorT | components.Publication;

/** @internal */
export const GetPublicationRequest$inboundSchema: z.ZodType<
    GetPublicationRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    id: z.string(),
});

/** @internal */
export type GetPublicationRequest$Outbound = {
    id: string;
};

/** @internal */
export const GetPublicationRequest$outboundSchema: z.ZodType<
    GetPublicationRequest$Outbound,
    z.ZodTypeDef,
    GetPublicationRequest
> = z.object({
    id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPublicationRequest$ {
    /** @deprecated use `GetPublicationRequest$inboundSchema` instead. */
    export const inboundSchema = GetPublicationRequest$inboundSchema;
    /** @deprecated use `GetPublicationRequest$outboundSchema` instead. */
    export const outboundSchema = GetPublicationRequest$outboundSchema;
    /** @deprecated use `GetPublicationRequest$Outbound` instead. */
    export type Outbound = GetPublicationRequest$Outbound;
}

/** @internal */
export const GetPublicationResponse$inboundSchema: z.ZodType<
    GetPublicationResponse,
    z.ZodTypeDef,
    unknown
> = z.union([components.ErrorT$inboundSchema, components.Publication$inboundSchema]);

/** @internal */
export type GetPublicationResponse$Outbound =
    | components.ErrorT$Outbound
    | components.Publication$Outbound;

/** @internal */
export const GetPublicationResponse$outboundSchema: z.ZodType<
    GetPublicationResponse$Outbound,
    z.ZodTypeDef,
    GetPublicationResponse
> = z.union([components.ErrorT$outboundSchema, components.Publication$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPublicationResponse$ {
    /** @deprecated use `GetPublicationResponse$inboundSchema` instead. */
    export const inboundSchema = GetPublicationResponse$inboundSchema;
    /** @deprecated use `GetPublicationResponse$outboundSchema` instead. */
    export const outboundSchema = GetPublicationResponse$outboundSchema;
    /** @deprecated use `GetPublicationResponse$Outbound` instead. */
    export type Outbound = GetPublicationResponse$Outbound;
}
